baseURL: "https://example.com"
languageCode: "no-nb"
title: "Hugo Novela"
pygmentsstyle: 'monokai'
metaDataFormat: yaml
defaultContentLanguage: no
languages:
  no:
    title: Oslo Barnemuseum
    weight: 2
  en:
    title: Childrens Museum of Oslo
    weight: 1

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
